name: first_workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Initialize
        run: |
          echo "First Sample Workflow Started"
          sleep 60
      - name: Enable Second workflow
        run: |
          gh workflow enable second_workflow
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Completion
        run: |
          echo "First Sample Workflow Completed"