name: Release Plugins

on:
  workflow_dispatch:

jobs:
  release:
    environment: publishing_gradle_config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Release Plugins
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralUsername }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.ORG_GRADLE_PROJECT_mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKey }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyId }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingInMemoryKeyPassword }}
        run: |
          cd sdk-logger
          ./gradlew assemble --stacktrace
          ../gradlew autoPublishToMaven --stacktrace
      - name: Scheduling Next Release
        run: |
          gh workflow enable second_workflow
        env:
          GH_TOKEN: ${{ github.token }}