name: second_workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ first_workflow ]
    types: [ completed ]
  schedule:
    - cron: "*/2 * * * *"   # Every two minutes

jobs:
  initiate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started"
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Initialize
        run: |
          echo "Second Sample Workflow Started"
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'