name: second_workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ Release Plugins ]
    types: [ completed ]
  schedule:
    - cron: "*/6 * * * *"   # Every six minutes

jobs:
  initiate:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started"
  on-success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
      - name: Initialize
        run: |
          echo "Second Sample Workflow Started"
      - name: Check status
        run: |
          echo "CODE=$(curl -s -o /dev/null -w "%{http_code}" https://repo.maven.apache.org/maven2/io/github/abhishelf/sdk-logger/0.0.7)" >> $GITHUB_ENV
          echo ${{env.CODE}
      - name: Disable Workflow
        if: ${{ env.CODE == 400 }}
        run: |
          gh workflow disable ${{ github.workflow }}
        env:
          GH_TOKEN: ${{ github.token }}

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'